In [8]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv("Resources/HR-Employee-Attrition.csv")
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [12]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [13]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [14]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [15]:
# merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [16]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes", "Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=78)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
# Create a Standard Scaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn=tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

2023-02-02 22:42:29.425659: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [23]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Train the model
fit_model = nn.fit(X_train, y_train, epochs=100)

2023-02-02 22:44:40.542553: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)

Epoch 1/100
35/35 [==============================] - 1s 1ms/step - loss: 59.7662 - accuracy: 0.6942
Epoch 2/100
35/35 [==============================] - 0s 885us/step - loss: 25.5604 - accuracy: 0.5100
Epoch 3/100
35/35 [==============================] - 0s 905us/step - loss: 6.2666 - accuracy: 0.5563
Epoch 4/100
35/35 [==============================] - 0s 917us/step - loss: 1.2221 - accuracy: 0.8276
Epoch 5/100
35/35 [==============================] - 0s 917us/step - loss: 0.7186 - accuracy: 0.8276
Epoch 6/100
35/35 [==============================] - 0s 1ms/step - loss: 0.6721 - accuracy: 0.8276
Epoch 7/100
35/35 [==============================] - 0s 868us/step - loss: 0.6418 - accuracy: 0.8276
Epoch 8/100
35/35 [==============================] - 0s 892us/step - loss: 0.6264 - accuracy: 0.8276
Epoch 9/100
35/35 [==============================] - 0s 915us/step - loss: 0.6153 - accuracy: 0.8276
Epoch 10/100
35/35 [==============================] - 0s 914us/step - loss: 0.6061 - accuracy: 0.8276
Epoch 11/100
35/35 [==============================] - 0s 915us/step - loss: 0.5978 - accuracy: 0.8276
Epoch 12/100
35/35 [==============================] - 0s 937us/step - loss: 0.5899 - accuracy: 0.8276
Epoch 13/100
35/35 [==============================] - 0s 910us/step - loss: 0.5824 - accuracy: 0.8276
Epoch 14/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5753 - accuracy: 0.8276
Epoch 15/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5686 - accuracy: 0.8276
Epoch 16/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5623 - accuracy: 0.8276
Epoch 17/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5563 - accuracy: 0.8276
Epoch 18/100
35/35 [==============================] - 0s 880us/step - loss: 0.5508 - accuracy: 0.8276
Epoch 19/100
35/35 [==============================] - 0s 874us/step - loss: 0.5454 - accuracy: 0.8276
Epoch 20/100
35/35 [==============================] - 0s 986us/step - loss: 0.5404 - accuracy: 0.8276
Epoch 21/100
35/35 [==============================] - 0s 880us/step - loss: 0.5356 - accuracy: 0.8276
Epoch 22/100
35/35 [==============================] - 0s 909us/step - loss: 0.5311 - accuracy: 0.8276
Epoch 23/100
35/35 [==============================] - 0s 918us/step - loss: 0.5269 - accuracy: 0.8276
Epoch 24/100
35/35 [==============================] - 0s 918us/step - loss: 0.5228 - accuracy: 0.8276
Epoch 25/100
35/35 [==============================] - 0s 911us/step - loss: 0.5191 - accuracy: 0.8276
Epoch 26/100
35/35 [==============================] - 0s 913us/step - loss: 0.5154 - accuracy: 0.8276
Epoch 27/100
35/35 [==============================] - 0s 975us/step - loss: 0.5120 - accuracy: 0.8276
Epoch 28/100
35/35 [==============================] - 0s 852us/step - loss: 0.5088 - accuracy: 0.8276
Epoch 29/100
35/35 [==============================] - 0s 902us/step - loss: 0.5058 - accuracy: 0.8276
Epoch 30/100
35/35 [==============================] - 0s 906us/step - loss: 0.5029 - accuracy: 0.8276
Epoch 31/100
35/35 [==============================] - 0s 837us/step - loss: 0.5002 - accuracy: 0.8276
Epoch 32/100
35/35 [==============================] - 0s 893us/step - loss: 0.4976 - accuracy: 0.8276
Epoch 33/100
35/35 [==============================] - 0s 886us/step - loss: 0.4951 - accuracy: 0.8276
Epoch 34/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4929 - accuracy: 0.8276
Epoch 35/100
35/35 [==============================] - 0s 869us/step - loss: 0.4907 - accuracy: 0.8276
Epoch 36/100
35/35 [==============================] - 0s 908us/step - loss: 0.4887 - accuracy: 0.8276
Epoch 37/100
35/35 [==============================] - 0s 864us/step - loss: 0.4867 - accuracy: 0.8276
Epoch 38/100
35/35 [==============================] - 0s 790us/step - loss: 0.4849 - accuracy: 0.8276
Epoch 39/100
35/35 [==============================] - 0s 943us/step - loss: 0.4832 - accuracy: 0.8276
Epoch 40/100
35/35 [==============================] - 0s 810us/step - loss: 0.4816 - accuracy: 0.8276
Epoch 41/100
35/35 [==============================] - 0s 884us/step - loss: 0.4801 - accuracy: 0.8276
Epoch 42/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4788 - accuracy: 0.8276
Epoch 43/100
35/35 [==============================] - 0s 829us/step - loss: 0.4774 - accuracy: 0.8276
Epoch 44/100
35/35 [==============================] - 0s 966us/step - loss: 0.4762 - accuracy: 0.8276
Epoch 45/100
35/35 [==============================] - 0s 925us/step - loss: 0.4750 - accuracy: 0.8276
Epoch 46/100
35/35 [==============================] - 0s 917us/step - loss: 0.4739 - accuracy: 0.8276
Epoch 47/100
35/35 [==============================] - 0s 889us/step - loss: 0.4729 - accuracy: 0.8276
Epoch 48/100
35/35 [==============================] - 0s 883us/step - loss: 0.4719 - accuracy: 0.8276
Epoch 49/100
35/35 [==============================] - 0s 939us/step - loss: 0.4710 - accuracy: 0.8276
Epoch 50/100
35/35 [==============================] - 0s 890us/step - loss: 0.4701 - accuracy: 0.8276
Epoch 51/100
35/35 [==============================] - 0s 899us/step - loss: 0.4693 - accuracy: 0.8276
Epoch 52/100
35/35 [==============================] - 0s 903us/step - loss: 0.4686 - accuracy: 0.8276
Epoch 53/100
35/35 [==============================] - 0s 896us/step - loss: 0.4679 - accuracy: 0.8276
Epoch 54/100
35/35 [==============================] - 0s 949us/step - loss: 0.4673 - accuracy: 0.8276
Epoch 55/100
35/35 [==============================] - 0s 858us/step - loss: 0.4667 - accuracy: 0.8276
Epoch 56/100
35/35 [==============================] - 0s 833us/step - loss: 0.4661 - accuracy: 0.8276
Epoch 57/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4655 - accuracy: 0.8276
Epoch 58/100
35/35 [==============================] - 0s 959us/step - loss: 0.4650 - accuracy: 0.8276
Epoch 59/100
35/35 [==============================] - 0s 898us/step - loss: 0.4646 - accuracy: 0.8276
Epoch 60/100
35/35 [==============================] - 0s 906us/step - loss: 0.4642 - accuracy: 0.8276
Epoch 61/100
35/35 [==============================] - 0s 945us/step - loss: 0.4638 - accuracy: 0.8276
Epoch 62/100
35/35 [==============================] - 0s 967us/step - loss: 0.4634 - accuracy: 0.8276
Epoch 63/100
35/35 [==============================] - 0s 946us/step - loss: 0.4630 - accuracy: 0.8276
Epoch 64/100
35/35 [==============================] - 0s 866us/step - loss: 0.4628 - accuracy: 0.8276
Epoch 65/100
35/35 [==============================] - 0s 980us/step - loss: 0.4624 - accuracy: 0.8276
Epoch 66/100
35/35 [==============================] - 0s 870us/step - loss: 0.4621 - accuracy: 0.8276
Epoch 67/100
35/35 [==============================] - 0s 884us/step - loss: 0.4619 - accuracy: 0.8276
Epoch 68/100
35/35 [==============================] - 0s 949us/step - loss: 0.4617 - accuracy: 0.8276
Epoch 69/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4615 - accuracy: 0.8276
Epoch 70/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4613 - accuracy: 0.8276
Epoch 71/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4611 - accuracy: 0.8276
Epoch 72/100
35/35 [==============================] - 0s 969us/step - loss: 0.4609 - accuracy: 0.8276
Epoch 73/100
35/35 [==============================] - 0s 890us/step - loss: 0.4608 - accuracy: 0.8276
Epoch 74/100
35/35 [==============================] - 0s 843us/step - loss: 0.4606 - accuracy: 0.8276
Epoch 75/100
35/35 [==============================] - 0s 837us/step - loss: 0.4605 - accuracy: 0.8276
Epoch 76/100
35/35 [==============================] - 0s 928us/step - loss: 0.4604 - accuracy: 0.8276
Epoch 77/100
35/35 [==============================] - 0s 808us/step - loss: 0.4603 - accuracy: 0.8276
Epoch 78/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4602 - accuracy: 0.8276
Epoch 79/100
35/35 [==============================] - 0s 927us/step - loss: 0.4601 - accuracy: 0.8276
Epoch 80/100
35/35 [==============================] - 0s 958us/step - loss: 0.4600 - accuracy: 0.8276
Epoch 81/100
35/35 [==============================] - 0s 964us/step - loss: 0.4600 - accuracy: 0.8276
Epoch 82/100
35/35 [==============================] - 0s 977us/step - loss: 0.4599 - accuracy: 0.8276
Epoch 83/100
35/35 [==============================] - 0s 884us/step - loss: 0.4598 - accuracy: 0.8276
Epoch 84/100
35/35 [==============================] - 0s 882us/step - loss: 0.4597 - accuracy: 0.8276
Epoch 85/100
35/35 [==============================] - 0s 949us/step - loss: 0.4597 - accuracy: 0.8276
Epoch 86/100
35/35 [==============================] - 0s 829us/step - loss: 0.4596 - accuracy: 0.8276
Epoch 87/100
35/35 [==============================] - 0s 869us/step - loss: 0.4596 - accuracy: 0.8276
Epoch 88/100
35/35 [==============================] - 0s 857us/step - loss: 0.4596 - accuracy: 0.8276
Epoch 89/100
35/35 [==============================] - 0s 888us/step - loss: 0.4595 - accuracy: 0.8276
Epoch 90/100
35/35 [==============================] - 0s 891us/step - loss: 0.4595 - accuracy: 0.8276
Epoch 91/100
35/35 [==============================] - 0s 976us/step - loss: 0.4595 - accuracy: 0.8276
Epoch 92/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4594 - accuracy: 0.8276
Epoch 93/100
35/35 [==============================] - 0s 954us/step - loss: 0.4594 - accuracy: 0.8276
Epoch 94/100
35/35 [==============================] - 0s 871us/step - loss: 0.4594 - accuracy: 0.8276
Epoch 95/100
35/35 [==============================] - 0s 765us/step - loss: 0.4594 - accuracy: 0.8276
Epoch 96/100
35/35 [==============================] - 0s 964us/step - loss: 0.4594 - accuracy: 0.8276
Epoch 97/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4593 - accuracy: 0.8276
Epoch 98/100
35/35 [==============================] - 0s 792us/step - loss: 0.4593 - accuracy: 0.8276
Epoch 99/100
35/35 [==============================] - 0s 888us/step - loss: 0.4593 - accuracy: 0.8276
Epoch 100/100
35/35 [==============================] - 0s 825us/step - loss: 0.4593 - accuracy: 0.8276

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.3898 - accuracy: 0.8723
Loss: 0.3898344933986664, Accuracy: 0.8722826242446899